-- MySQL Script generated by MySQL Workbench
-- Mon Feb 19 07:22:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema myflaskapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myflaskapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myflaskapp` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema rubiconsensors_0-1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rubiconsensors_0-1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rubiconsensors_0-1` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
USE `myflaskapp` ;

-- -----------------------------------------------------
-- Table `myflaskapp`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myflaskapp`.`articles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `author` VARCHAR(100) NULL DEFAULT NULL,
  `body` TEXT NULL DEFAULT NULL,
  `create_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `myflaskapp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myflaskapp`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `username` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `register_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;

USE `rubiconsensors_0-1` ;

-- -----------------------------------------------------
-- Table `rubiconsensors_0-1`.`chartdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubiconsensors_0-1`.`chartdata` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `year` VARCHAR(100) NULL DEFAULT NULL,
  `probe1` INT(10) NULL DEFAULT NULL,
  `probe5` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rubiconsensors_0-1`.`easy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubiconsensors_0-1`.`easy` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rubiconsensors_0-1`.`electron1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubiconsensors_0-1`.`electron1` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ISO8601` VARCHAR(100) NULL DEFAULT NULL,
  `probe1` DECIMAL(5,2) NULL DEFAULT NULL,
  `probe2` DECIMAL(5,2) NULL DEFAULT NULL,
  `probe3` DECIMAL(5,2) NULL DEFAULT NULL,
  `probe4` DECIMAL(5,2) NULL DEFAULT NULL,
  `probe5` DECIMAL(5,2) NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rubiconsensors_0-1`.`googledata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubiconsensors_0-1`.`googledata` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `year` VARCHAR(100) NULL DEFAULT NULL,
  `probe 5` VARCHAR(100) NULL DEFAULT NULL,
  `probe 1` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rubiconsensors_0-1`.`googledata2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubiconsensors_0-1`.`googledata2` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `year` VARCHAR(100) NULL DEFAULT NULL,
  `probe1` VARCHAR(100) NULL DEFAULT NULL,
  `probe5` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rubiconsensors_0-1`.`pipe_sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubiconsensors_0-1`.`pipe_sensor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ISO8601` VARCHAR(100) NULL DEFAULT NULL,
  `data` INT(5) NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rubiconsensors_0-1`.`sensor_a`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubiconsensors_0-1`.`sensor_a` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `time` DECIMAL(6,5) NULL DEFAULT NULL,
  `arduino` INT(100) NULL DEFAULT NULL,
  `probe1` DECIMAL(5,2) NULL DEFAULT NULL,
  `probe2` DECIMAL(5,2) NULL DEFAULT NULL,
  `probe3` DECIMAL(5,2) NULL DEFAULT NULL,
  `probe4` DECIMAL(5,2) NULL DEFAULT NULL,
  `probe5` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rubiconsensors_0-1`.`sensors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubiconsensors_0-1`.`sensors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(100) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `create_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rubiconsensors_0-1`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubiconsensors_0-1`.`test` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(80) NULL DEFAULT NULL,
  `email` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rubiconsensors_0-1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rubiconsensors_0-1`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NULL DEFAULT NULL,
  `username` VARCHAR(30) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `register_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `electron1_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_electron1_idx` (`electron1_id` ASC),
  CONSTRAINT `fk_users_electron1`
    FOREIGN KEY (`electron1_id`)
    REFERENCES `rubiconsensors_0-1`.`electron1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
